In [ ]:
# This is a magic function in Python that embeds figures within the notebook instead (inline) of in its own cell
%matplotlib inline

In [ ]:
# local imports
import numpy as np

# From Matlab to Python

Transitioning from using Matlab to using Python can be daunting at first! However, many of the methods available in Matlab have been rewritten in python. This notebook will explore the similarities & differences between these two languages.

    
# Why use Matlab?

    1) Toolboxes provided by Mathworks are supported and easy to install.
    2) (usually) No open-source packages to manage and include.
    3) Co-workers use it &/or you already know how it use it.

# Why use Python?

    1) Python is Free, Open Source, & very popular (easy to find answers & code examples)
    2) Python has all the computational power required for scientific tasks that Matlab does
    3) Python has more features (general purpose) - its not just for scientific/enginering/mathematical workflows
    
# Matlab & Python Similarities:

    1) Both are interpreted languages - goes through an interpreter (no compiling required)
    2) Both are easy to read 
    3) Both have a large standard library


# Matlab & Python Differences:

    1) Indexing starts at 0 in Python and 1 in Matlab.
    2) Matlab uses semicolons to suppress output. This is not required in Python.
    3) Matlab is matrix & linear algebra focused so most data types are arrays. Python has many built-in data types to take advantage of.
    4) Matlab has a built-in IDE (Integrated Development Enviornment) while Python does not
    5) Python uses [] for indexing & () for function calls while Matlab uses () for both

# From Matlab to Python - Arrays

Using lists and NumPy can be very useful when making the transition from Matlab to Python! NumPy ndarray manipulations are ~50x faster than list manipulation and they take up less space. In this section, we will learn how to use NumPy ndarrays. Please see [Tutorial 1](https://mybinder.org/v2/gh/hschovanec-usgs/python_binder_tutorials/master) for more information on lists and NumPy.

## Contents
- [Array Creation](#Array-Creation)
- [Array Concatenation](#Array-Concatenation)
- [Array Slicing](#Array-Slicing)
- [Matrix Multiplication](#matrix)

### Array Creation

<table>
   <tr>
      <th>Example</th>
      <th>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Matlab&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</th>
      <th>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Python&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</th>
      <th>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Output&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</th>
   </tr>
   <tr>
      <td>1</td>
      <td>a = [1, 2, 3, 4] or a = [1 2 3 4]</td>
      <td>b = np.array([1,2,3,4])</td>
      <td>[1 2 3 4]</td>
   </tr>
   <tr>
      <td>2</td>
      <td>b = linspace(1, 4, 2)</td>
      <td>b = np.linspace(1, 4, 2)</td>
      <td>[1 4]</td>
   </tr>
   <tr>
      <td>3</td>
      <td>c = zeros(2)</td>
      <td>c = np.zeros(2)</td>
      <td>[0 0]</td>
   </tr>
   <tr>
      <td>4</td>
      <td>d = rand(2)</td>
      <td>d = np.random.rand(2)</td>
      <td>[* *]</td>
   </tr>
   <tr>
      <td>5</td>
      <td>e = eye(3)</td>
      <td>e = np.identity(3)</td>
      <td>[[1 0 0]<br>[0 1 0]<br>[0 0 1]]</td>
   </tr>
   <tr>
      <td>6</td>
      <td>f = diag([1 2 3])</td>
      <td>f = np.diag([1, 2, 3])</td>
      <td>[[1 0 0]<br>[0 2 0]<br>[0 0 3]]</td>
   </tr>
</table>

In [ ]:
## Example 1
a = np.array([1,2,3,4])
print("Example 1:", a)

## Example 2
b = np.linspace(1, 4, 2)
print("Example 2:", b)

## Example 3
c = np.zeros(2)
print("Example 3:", c)

## Example 4
d = np.random.rand(2)
print("Example 4:", d)

## Example 5
e = np.identity(3)
print("Example 5:\n", e)

## Example 6
f = np.diag([1, 2, 3])
print("Example 6:\n", f)

### Array Concatenation

Concatenation in python is similar to the `cat` method in Matlab. This is used for joining arrays along an existing axis. Note: The indexing for axes begins at 0 rather than 1.

<table>
   <tr>
      <th>Example</th>
      <th>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Matlab&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</th>
      <th>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Python&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</th>
      <th>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Output&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</th>
   </tr>
   <tr>
      <td>1</td>
      <td>a1 = ones(3)<br>a2 = zeros(3)<br>a = cat(1, a1, a2)</td>
      <td>a1 = np.ones((3, 3))<br>a2 = np.zeros((3, 3))<br>a = np.concatenate((a1, a2), axis=0)</td>
      <td>[[1 1 1]<br>
 [1 1 1]<br>
 [1 1 1]<br>
 [0 0 0]<br>
 [0 0 0]<br>
 [0 0 0]]</td>
   </tr>
    <tr>
      <td>2</td>
      <td>b1 = ones(3)<br>b2 = zeros(3)<br>b = cat(2, b1, b2)</td>
      <td>b1 = np.ones((3, 3))<br>b2 = np.zeros((3, 3))<br>b = np.concatenate((b1, b2), axis=1)</td>
      <td> [[1 1 1 0 0 0]<br>
 [1 1 1 0 0 0]<br>
 [1 1 1 0 0 0]]</td>
   </tr>
</table>

In [ ]:
## Example 1
a1 = np.ones((3, 3))
a2 = np.zeros((3, 3))
a = np.concatenate((a1, a2), axis=0) # join by column; this is the default.
print('a1 =\n', a1)
print('a2 =\n', a2)
print("Example 1:\n", a)

## Example 2
b = np.concatenate((a1, a2), axis=1) # join by row
print("Example 2:\n", b)

### Array Slicing

<table>
   <tr>
      <th>Example</th>
      <th>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Matlab&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</th>
      <th>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Python&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</th>
      <th>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Output&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</th>
   </tr>
   <tr>
      <td>1</td>
      <td>a1 = [16 5 9 4 2 11 7 14]<br> a = a1(3:7)</td>
      <td>a1 = np.array([16, 5, 9, 4, 2, 11, 7, 14])<br> a = a1[2:7]</td>
      <td>[ 9  4  2 11  7]</td>
   </tr>
    <tr>
      <td>2</td>
      <td>b1 = [16 5 9 4 2 11 7 14]<br> b = b1(1:2:end)</td>
      <td>b1 = np.array([16, 5, 9, 4, 2, 11, 7, 14])<br> b = b1[0::2]</td>
        <td>[16  9  2  7]</td>
   </tr>
    <tr>
      <td>3</td>
      <td>c1 = [16 5 9 4 2 11 7 14]<br> c = c1(end:-1:1) </td>
      <td>c1 = np.array([16, 5, 9, 4, 2, 11, 7, 14])<br> c = c1[::-1]</td>
        <td>[14  7 11  2  4  9  5 16]</td>
   </tr>
</table>

In [ ]:
## Example 1 - get items from columns 3 to 7
a1 = np.array([16, 5, 9, 4, 2, 11, 7, 14])
a = a1[2:7]
print("Example 1 = \n", a)

## Example 2 - get every 2nd item start from item 1
b1 = np.array([16, 5, 9, 4, 2, 11, 7, 14])
b = b1[0::2]
print("Example 2 = \n", b)

## Example 3 - reverse the order of items in the array
c1 = np.array([16, 5, 9, 4, 2, 11, 7, 14])
c = c1[::-1]
print("Example 3 = \n", c)

### Quiz 1

**Create: 1) a random 3x4 array, 2) a random 2x4 array, 3) concatenate the arrays by the 0 index, and 4) print row 3 columns 2 to 4**

<details>
  <summary>SEE SOLUTION</summary>
    
```
a = np.random.rand(3,4)
print('a\n',a)
b = np.random.rand(2,4)
print('b\n',b)
c = np.concatenate((a, b), axis=0)
print('c\n',c)
d = c[3,1:4]
print('Answer = \n',d)
```
</details>

In [ ]:
## Your Code Here

<a id='matrix'></a>
### Matrix Multiplication

In Python, the NumPy library must also be used for creating a matrix and doing matrix manipulation.

| Example | Matlab | Python | Output      
| :- |:- | :- | :-
|1|a = [5,4 ; 2,7];<br> b = [1,11;6,10];<br> c = a * b |a = np.matrix(((5,4), (2,7)))<br> b = np.matrix(((1,11), (6, 10)))<br> c = a * b | [[29 95]<br>[44 92]]


In [ ]:
## Example 1
a = np.matrix(((5,4), (2, 7)))
print(f'Matrix A = \n {a}')
b = np.matrix(((1,11), (6, 10)))
print(f'Matrix B = \n {b}')
c = a * b
print(f'A * B = \n {c}')
print(f'Product:\n {np.dot(a,b)}')

# element wise operations:
print(f'Multiplication:\n {np.multiply(a,b)}')
print(f'Addition:\n {np.add(a,b)}')

# From Matlab to Python - Looping, If Statements, & Functions
Let's look at some quick examples of looping, if statements, as well as writing and calling functions. More details are available in [Tutorial 1](https://mybinder.org/v2/gh/hschovanec-usgs/python_binder_tutorials/master).

## Contents
- [Looping & If Statements](#looping)
- [Functions](#Functions)

<a id='looping'></a>
### Looping & If Statements
Indentation and using colons are important when looping and using if statements in Python!

| Example | Matlab | Python | Output      
| :- |:- | :- | :-
|1| for i=1:5 <br>&nbsp;&nbsp;&nbsp;&nbsp;a(i) = i; <br>end|a = [] <br>for i in range(1,6): <br>&nbsp;&nbsp;&nbsp;&nbsp;a.append(i) | [1, 2, 3, 4, 5]
|2|a = 1;<br>b = 4;<br>if a == 1 \|\| b == 5 <br>&nbsp;&nbsp;&nbsp;&nbsp;fprintf('a is 1 or b is 5')<br>end |a = 1<br> b = 4<br>if a == 1 or b ==5:<br>&nbsp;&nbsp;&nbsp;&nbsp;print('a is 1 or b is 5') | a is 1 or b is 5

In [ ]:
## Example 1 - for loop
a = [] # must initialize array/list
for i in range(1,6):
    a.append(i)
print(f'Example 1:\n {a}')

## Example 2 - if statement
a = 1
b = 4
if a == 1 or b ==5:
    print('a is 1 or b is 5')

### Quiz 2
**Loop through an array of values from 1 to 6 and print out each even number.** Hint: you can use the Modulo Operator (the % sign) to determine the remainder of a divsion.

<details>
  <summary>SEE SOLUTION</summary>
    
```
a = np.array([1,2,3,4,5,6])
print("array =\n",a)
for i in a:
    if i % 2 == 0:
        print(f'{i} is an even number')
```
</details>

In [ ]:
## Your Code Here

### Functions

In Python the main function and other function definitions can be in the same file, whereas in Matlab the main and function definitions are typically in separate files. In Matlab it is common to have one file for each function where the name of the function and file is the same. In Python, however, you can have multiple functions in one file with no name dependencies! More details on writing functions in Python are available in [Tutorial 1](https://mybinder.org/v2/gh/hschovanec-usgs/python_binder_tutorials/master). Note: it is possible in Matlab to include multiple functions in one file by returning function handles to local functions by making them fields of a struct ([example here](#https://stackoverflow.com/questions/3569933/is-it-possible-to-define-more-than-one-function-per-file-in-matlab-and-access-t)).

| Example | Matlab | Python | Output      
| :- |:- | :- | :-
|1| function z = my_func(x,y)<br> z =x + y | def my_func(x,y):<br>&nbsp;&nbsp;&nbsp;&nbsp;z =x + y<br>&nbsp;&nbsp;&nbsp;&nbsp;return z | z is returned

In [ ]:
## Example 1
def my_func(x,y):
    z = x + y
    return z

# call the function
my_func(2,3)

# From Matlab to Python - Basic Plotting

Lets look at some quick examples of 2D & 3D plotting! In general, plotting is similar but Python requires the use of external libraries. Commands like `hold on` and using semicolons is not necessary like it is in Matlab. In Python, the figure does not automatically open in a separate display when running a script like it does in Matlab. You will have to save the figure in your code. However, if using Jupyter or ipython it is possible for the figure to appear in line or in a separate window.

## Contents
- [2D Plotting](#2d)
- [3D Plotting](#3d)

<a id='2d'></a>
### 2D Plotting

Here are Python equivalencies of plots using Matplotlib from examples in the Matlab documentation (https://www.mathworks.com/help/matlab/ref/plot.html). Examples of plotting maps in Python using Cartopy will also be covered.

## Contents
- [Line Plot](#Line-Plot)
- [Multiple Line Plot](#Multiple-Line-Plot)
- [Line Styling](#Line-Styling)
- [Multiple Axes](#Multiple-Axes)
- [Maps](#Maps)

In [ ]:
# 2D plotting Realted Libraries
import numpy as np
import matplotlib.pyplot as plt
# for mapping:
import cartopy
import cartopy.crs as ccrs
import cartopy.feature as cfeature

## Line Plot

| Example | Matlab | Python     
| :- |:- | :-
|1|x = linspace(0,4*pi,100);<br>y = cos(x);<br>plot(x,y)<br>ylabel('cos(x)')<br>xlabel('x') | x = np.linspace(0,4*np.pi,100)<br>y = np.cos(x)<br>plt.plot(x,y)<br>plt.ylabel('cos(x)')<br>plt.xlabel('x')<br>plt.show()

In [ ]:
## Example 1
x = np.linspace(0,4*np.pi,100)
y = np.cos(x)
plt.figure(1)
plt.plot(x,y)
plt.ylabel('cos(x)')
plt.xlabel('x')
plt.title('Example 1')
plt.show()

## Multiple Line Plot

In [ ]:
## Example 2
x1 = np.linspace(-2*np.pi, 2*np.pi)
y1 = np.sin(x1)
y2 = np.cos(x1)

### Quiz 3
**Execute the cell above then plot both x1 and y1 together in one plot**

<details>
  <summary>SEE SOLUTION</summary>
    
```
plt.figure(2)
plt.plot(x1, y1, x1, y2)
plt.title('Example 2')
plt.show()
```
</details>

In [ ]:
# Your Code Here

## Line Styling

In [ ]:
## Example 3
x = np.arange(0, 2*np.pi, np.pi/100)
y1 = np.sin(x)
y2 = np.sin(x-0.25)
y3 = np.sin(x-0.5)

plt.figure(3)
plt.plot(x, y1,'k', x, y2, '--m', x, y3, ':c')
plt.title('Example 3')
plt.show()

## Multiple Axes

In [ ]:
## Example 4
x = np.linspace(0,3)
y1 = np.sin(5*x)
y2 = np.sin(15*x)

f, (ax1, ax2) = plt.subplots(2, 1, sharex=True)
ax1.plot(x1, y1)
ax1.set_title('Top Plot')
ax1.set_ylabel('sin(5x)')

ax2.scatter(x1, y2)
ax2.set_title('Bottom Plot')
ax2.set_ylabel('sin(15x)')
plt.show()

## Maps

You can also make maps in Python using Cartopy! Cartopy was developed for improving the visualization of geographically located scientific data. The projection must be defined when creating axes. Features like rivers, borders, coastlines can also be easily added from the cartopy.feature library.

In [ ]:
## Example 1
plt.figure()
ax = plt.axes(projection=ccrs.PlateCarree())
ax.coastlines()
ax.add_feature(cfeature.BORDERS, linestyle=':')
ax.add_feature(cfeature.RIVERS)
ax.add_feature(cfeature.LAND)
plt.show()

In [ ]:
## Example 2 
projections = [ccrs.Robinson(),
               ccrs.Mercator(),
               ccrs.LambertConformal()
              ]
for proj in projections:
    plt.figure()
    ax = plt.axes(projection=proj)
    ax.stock_img()
    ax.coastlines()
    ax.set_title(f'{type(proj)}')

<a id='3d'></a>
### 3D Plotting

3D plotting in Python is similar to 3D plotting in Matlab. Here are a few examples of 3D plotting in Python. There are a variety of different 3D plotting packages to choose from, here we will use 3D plotting with Matplotlib and follow examples from https://jakevdp.github.io/PythonDataScienceHandbook/04.12-three-dimensional-plotting.html.

## Contents
- [Figure Basics](#Figure-Basics)
- [Line and Scatter Plots](#Line-&-Scatter-Plots)
- [ContourPlot](#Contour-Plot)
- [Wirefram Plot](#Wireframe-Plot)
- [Surface Plot](#Surface-Plot)

### Figure Basics

In [ ]:
# 3D plotting related libaries:
# %matplotlib notebook is required for being able to interact with 3D plots
%matplotlib notebook
from mpl_toolkits import mplot3d
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
# The projection='3d' must be used for creating a 3D axes
fig = plt.figure()
ax = plt.axes(projection='3d')
ax.set_xlabel('x')
ax.set_ylabel('y')
ax.set_zlabel('z')
ax.set_title('3D Plot')
plt.show()

### Line & Scatter Plots

In [ ]:
fig = plt.figure()
ax = plt.axes(projection='3d')

# Create data for a 3D line
zline = np.linspace(0, 25, 1000)
xline = np.sin(zline)
yline = np.cos(zline)
ax.plot3D(xline, yline, zline, 'gray')

# Create data for 3D scattered points
zdata = 25 * np.random.random(100)
xdata = np.sin(zdata) + 0.1 * np.random.randn(100)
ydata = np.cos(zdata) + 0.1 * np.random.randn(100)
ax.scatter3D(xdata, ydata, zdata, c=zdata, cmap='Reds')
plt.show()

### Contour Plot

In [ ]:
def f(x, y):
    return np.sin(np.sqrt(x ** 2 + y ** 2))

x = np.linspace(-6, 6, 30)
y = np.linspace(-6, 6, 30)

X, Y = np.meshgrid(x, y)
Z = f(X, Y)

In [ ]:
fig = plt.figure()
ax = plt.axes(projection='3d')
ax.contour3D(X, Y, Z, 50, cmap='binary')
ax.set_xlabel('x')
ax.set_ylabel('y')
ax.set_zlabel('z')
plt.show()

### Wireframe Plot

In [ ]:
fig = plt.figure()
ax = plt.axes(projection='3d')
ax.plot_wireframe(X, Y, Z, color='black')
ax.set_title('wireframe')
plt.show()

### Surface Plot

In [ ]:
fig = plt.figure()
ax = plt.axes(projection='3d')
ax.plot_surface(X, Y, Z, rstride=1, cstride=1,
                cmap='viridis', edgecolor='none')
ax.set_title('surface')
plt.show()

### Quiz 4
**Plot Alaska seismicity. Read in the file Alaska_EQ.xyz and plot using 1) a 3D scatter plot, and 2) Cartopy to plot data in map view using a Mercator projection. Bonus points if you plot eathquake magnitude by circle size and depth by colour.** Alaska_EQ.xyz has columns longitude, latitude, positive depth (km), magnitude. Hint: [Tutorial 1](https://mybinder.org/v2/gh/hschovanec-usgs/python_binder_tutorials/master) covered reading in data.

<details>
  <summary>SEE SOLUTION</summary>
    
```
# Read in data and parse:
hypo = np.genfromtxt('Alaska_EQ.xyz')
lon = hypo[:,0]
lat = hypo[:,1]
depth = hypo[:,2]
mag = hypo[:,3]
lonMax = lon.max()+2
lonMin = lon.min()-2
latMax = lat.max()+2
latMin = lat.min()-2
lonMid = (lonMax + lonMin)/2

# 3D scatter plot:
fig = plt.figure()
ax = plt.axes(projection='3d')
p = ax.scatter3D(lon, lat, depth*-1, c=depth*-1, s=mag, cmap='magma')
#fig.colorbar(p)
ax.set_xlabel('lon')
ax.set_ylabel('lat')
ax.set_zlabel('Negative Depth')
ax.set_title('Seismicity of Alaska')
plt.show()

# Cartopy Map:
fig = plt.figure()
# define map extent:
img_extent = (lonMin, lonMax, latMin, latMax)
# define projection & plot:
ax = plt.axes(projection=ccrs.Mercator(central_longitude=lonMid))
ax.scatter(lon,lat,c=depth*-1, s=mag*2, cmap='magma',transform=ccrs.PlateCarree())
ax.set_extent(img_extent)
# set basemap & add coastlines & borders:
ax.stock_img()
ax.coastlines()
ax.add_feature(cfeature.BORDERS, linestyle=':')
# add lon lat grid lines and labels:
ax.gridlines(crs=ccrs.PlateCarree(), draw_labels=True,linewidth=0.5, color='gray', alpha=0.5, linestyle='--')
plt.show()
```
</details>

In [ ]:
# Your Code Here